### ISSUE TITLE
Batch 2: Implement Contract Write 

### ISSUE THREAD

**Issue by dblodorn** [public-assembly/zora-drops-utils#12]
Utilizing wagmi create a series of proxy hooks accessible through `DropsContractProvider` upon batch completion a second cut will be published to npm.

- [x] #30
- [x] #32
- [x] #26
- [x] #37
- [x] #31 
- [x] #39

**Comment by 0xTranqui** [comment]
@dblodorn see 15 min front end focused loom below that provides details on the new “getListings” view call that will be what we are querying from the curation contract. tldr is instead of an array of an addresses, it will be an array of structs that carries info that tells u if the object being curated is an edition or generative edition, and the contract addresses (AND tokenId if it’s a generative edition). will need 2 data fetching strategies, one for editions (which seems like it’s already done?), and one for generative editions (which will likely have to query the zora indexer for the metadata and the subgraph for the sales config)

loom: https://www.loom.com/share/92fd2144b65f41669ddd390b6d4902ca

lemme know if u need further clarification than what’s provided in the loom !!

**Comment by 0xTranqui** [comment]
![6E218FCD-9F8D-4056-8A9D-740F3FB34BF8](https://user-images.githubusercontent.com/93691906/193177585-15ba86d8-8ccf-4399-98b0-4da3035f9163.png) this is what the structs will look like that I refer to in the comment above. Explain it in detail in the loom
